(module graph-layout scheme
  (require srfi/1 srfi/43 "helper-functions.scm")
  
  ;;; For force-directed layout we layout the points randomly and then
  ;;; iterate until we acheive a low-energy layout.
  (define (rand-points n)
    (let ((p (list-tabulate n (lambda _ (list (random) (random))))))
      (if (unique? p) 
          p
          (rand-points n))))

  ;; All of our layout functions use closures passed in as arguments to
  ;; manipulate graphs. This way, they will work for any graph
  ;; representation given the proper accessor function.
  (define (random-layout nodes get-neighbors)
    (rand-points (length nodes)))
  
  ;; We assume that the number of nodes is a perfect square and the
  ;; grid is generated by the square-grid function. Otherwise results
  ;; may vary
  (define (grid-layout nodes get-neighbors)
    (let* ((size (sqrt (length nodes)))
           (scale (/ 1 size))
           (column -1))
      (map (lambda (node)
             (v+ (/ scale 2)
                 (v* (list (remainder (inc! column) size)
                           (quotient column size))
                     scale)))
             nodes)))

  (provide random-layout grid-layout))